version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    command: ./bin/rails s -p 5000 -b '0.0.0.0'
    environment:
      ELASTICSEARCH_URL: 'elasticsearch:9200'
    depends_on:
      - db
      - elasticsearch
  db:
    image: postgres:9.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: magic_development
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - '9200:9200'
      - '9300:9300'
